name: flopy_env
channels:
  - conda-forge
  - defaults
dependencies:
  - fiona=1.9.4
  - flopy=3.4.2
  - gdal=3.7.2
  - geopandas=0.14.0
  - geopandas-base=0.14.0
  - numpy=1.22.4
  - pandas=2.1.0
  - pip=23.2.1
  - pyproj=3.6.0
  - python=3.10.13
  - python-dateutil=2.8.2
  - scikit-learn=1.3.0
  - scipy=1.11.2
   - shapely=2.0.1
  - six=1.16.0
  - snappy=1.1.10
  - sqlite=3.41.2
